version: '2'
services:
  tinkuy-nodebb:
    build: ./nodebb
    links:
      - tinkuy-redis
    ports:
      - "4567:4567"
    volumes: 
      - tinkuy-nodebb:/nodebb

  tinkuy-redis:
    image: redis:3
    volumes: 
      - tinkuy-redis:/data

  nginx:
    image: nginx
    volumes:
      - /solsort/gh/whale/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - tinkuy-nodebb
    ports:
      - "0.0.0.0:80:80"
volumes:
  tinkuy-nodebb: {"driver": "local"}
  tinkuy-redis: {"driver": "local"}
