version: '2'
services:
  tinkuy-nodebb:
    restart: always
    build: ./nodebb
    links:
      - tinkuy-redis
    ports:
      - "4567:4567"
    volumes:
      - ./config/nodebb.config.json:/nodebb/config.json:ro
      - tinkuy-nodebb:/nodebb/public/uploads

  tinkuy-redis:
    restart: always
    image: redis:3
    volumes: 
      - tinkuy-redis:/data

  nginx:
    restart: always
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - tinkuy-nodebb
    ports:
      - "0.0.0.0:80:80"
volumes:
  tinkuy-nodebb: {"driver": "local"}
  tinkuy-redis: {"driver": "local"}
